version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  club-service:
    build:
      context: ./Club-Service
    ports:
      - "5002:5002"
    env_file:
      - ./Club-Service/.env
    depends_on:
      - mongo

  auth-service:
    build:
      context: ./Authentication_Microservice
    ports:
      - "5001:5001"
    env_file:
      - ./Authentication_Microservice/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
